version: "3"

services:
  backend:
    container_name: frt_backend
    restart: always
    image: zolin17/frt:lmn
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 120"
    ports:
      - "8010:8000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
  frontend:
    container_name: frt_frontend
    restart: always
    image: zolin17/frt:lmn
    working_dir: /app/web/frontend
    command: sh -c "npm start"
    ports:
      - "3010:3000"
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: frt_redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 5G
