version: "3"

services:
  backend:
    container_name: frt_backend
    restart: always
    image: zolin17/frt-web:dev
    command: sh -c "python run_api.py"
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    container_name: frt_frontend
    restart: always
    image: zolin17/frt-web:dev
    working_dir: /app/web/frontend
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    env_file:
      - .env
